Shadow CL:DEFUN during make-host-1
So we don't need to put #-sb-xc-host on VALUES declarations.

CCL as host would fail thusly without the DEFUN interceptor:
;Compiler warnings for "src/compiler/ctype.lisp" :
;   In DEFINITION\-TYPE: Unknown or invalid declaration (VALUES FUN\-TYPE &OPTIONAL)
;   In NOTE\-FUN\-USE: Unknown or invalid declaration (VALUES APPROXIMATE\-FUN\-TYPE)
;   In VALID\-APPROXIMATE\-TYPE: Unknown or invalid declaration (VALUES BOOLEAN BOOLEAN)
> Error: FAILURE-P was set when creating "obj/from-host/src/compiler/ctype.lx64fsl".