Fix MACROEXPANDing alien structure type redefinition
Previously, MACROEXPANDing the redefinition of an alien structure type
signaled an unintended error: while trying to signal the continuable
"Incompatible alien record type definition"
error, *RECORD-TYPES-ALREADY-UNPARSED* was unbound, causing
UNPARSE-ALIEN-RECORD-FIELD to fail.