Strengthen type constraint on *MACROEXPAND-HOOK* and *DEBUGGER-HOOK*
Aside from the literal absence of the adjective "extended" in front of
"function designator", there are other indications that the spec didn't mean
"extended function designator" for these two hook functions:

* The CLHS entry on *MACROEXPAND-HOOK* suggests to save the previous value and
  invoke it as part of a custom hook to preserve behavior that the default hook
  imparted. But FUNCALL can not call an extended function designator, so users
  would need to invoke it with a non-trivial incantation
    (funcall (coerce saved-hook 'function) ...)
  [which also happens not to work in an implementations I tested]

  Given the suggestion's lack of caution about a not-necessarily-funcallable
  object, we could infer that:
  - the hook is in fact directly amenable to funcall, OR
  - the spec writer merely forget to mention that generalized names are not
    funcallable (and you really need the portable formula above, and must
    discover it for yourself), or didn't think it needed mentioning.

  Occam's razor favors the first explanation. As to the latter, an accident of
  omission would not hold much sway, and it requires _two_ assumptions to say
  it was an oversight- one that "extended" was itself an accidental omission.
  But we're not in a position of trying to argue that the text is wrong and that
  it was simply two tiny omissions - our code doesn't match the spec as it is,
  not as it might theoretically be.

* It's not portable to assume that you can do this unusual thing. Test case:
  (defun (setf z) (&rest args) (format t "[Got ~s]~%" args) t)
  (let ((*macroexpand-hook* '(setf z))) (compile nil '(lambda () (defun f ()))))
CCL:
> Error: (SETF Z) is not of type (OR SYMBOL FUNCTION), and can't be FUNCALLed or APPLYed
ABCL:
  The function NIL is undefined.

There is a counterargument to this simplification: MACROEXPAND-1 says
  "The value of *macroexpand-hook* is coerced to a function"
But the portability issue should carry the most weight.