Add -std=gnu99
Required by a recent change:
  gencgc.c: In function ‘pin_call_chain_and_boxed_registers’:
  gencgc.c:3678:9: error: ‘for’ loop initial declarations are only allowed in C99 mode
           for (unsigned i = 0; i < (sizeof(boxed_registers) / sizeof(int)); i++) {
           ^
  gencgc.c:3678:9: note: use option -std=c99 or -std=gnu99 to compile your code